services:
  - type: web
    name: samarth-assignment-8-gym-management-api
    env: node
    buildCommand: cd Samarth_Navale_150096725148 && npm install
    startCommand: cd Samarth_Navale_150096725148 && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
